/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import ErrorClass.ErrorChecker;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PasswordLable = new javax.swing.JLabel();
        FirstNameLable = new javax.swing.JLabel();
        SurnameLable = new javax.swing.JLabel();
        UsernameLable = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaErrorUsername = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaErrorPassword = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaErrorFirstName = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaErrorSurname = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));

        jLabel1.setText("Register Window");

        PasswordLable.setText("Password:");

        FirstNameLable.setText("First name:");

        SurnameLable.setText("Surname:");

        UsernameLable.setText("Username:");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txaErrorUsername.setColumns(20);
        txaErrorUsername.setRows(5);
        jScrollPane1.setViewportView(txaErrorUsername);

        txaErrorPassword.setColumns(20);
        txaErrorPassword.setRows(5);
        jScrollPane2.setViewportView(txaErrorPassword);

        txaErrorFirstName.setColumns(20);
        txaErrorFirstName.setRows(5);
        jScrollPane3.setViewportView(txaErrorFirstName);

        txaErrorSurname.setColumns(20);
        txaErrorSurname.setRows(5);
        jScrollPane4.setViewportView(txaErrorSurname);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(FirstNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFirstName))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(PasswordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPassword))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(UsernameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SurnameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(UsernameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(PasswordLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(FirstNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(SurnameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        //**************************************************************************************//
        //Error checking class
        ErrorChecker Error = new ErrorChecker();
        //**************************************************************************************//
        
        //**************************************************************************************//
        //check Username field
        txaErrorUsername.setText(Error.checkUserName(txtUsername.getText()));
        //**************************************************************************************//
        
        //**************************************************************************************//
        //check Password field
        txaErrorPassword.setText(Error.checkPasswordComplexity(txtPassword.getText()));
        //**************************************************************************************//
        
        //**************************************************************************************//
        //check First name field
        txaErrorFirstName.setText(Error.ErrorRegisterFirstName(txtFirstName.getText()));
        //**************************************************************************************//
        
        //**************************************************************************************//
        //check surname field
        txaErrorSurname.setText(Error.ErrorRegisterSurname(txtSurname.getText()));
        //**************************************************************************************//
        
        //**************************************************************************************//
        //creates control variable
        //boolean control = false;
        
        //checks username, password, first name and surname
        
        String registerResult = Error.registerUser(getTxtUsername(), getTxtPassword(), getTxtFirstName(), getTxtSurname());

        if (registerResult.equals("The four above conditions have been met and the user has been registered successfully.")) {
        
            
             try {
        // Save the data to a text file 
        FileWriter writer = new FileWriter("LoginDetails.txt", true);
        
        writer.write(txtUsername.getText() + "#" + txtPassword.getText() + "#" + txtFirstName.getText() + "#" + txtSurname.getText());
        writer.write("");

        // Close the writer to ensure changes are flushed to the file
        writer.close();
        
        // notify user that it is done
        JOptionPane.showMessageDialog(null, "Registration successful. You can now log in.");
        
    } catch (IOException ex) {
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
    }
            
            //close window
        Login login = new Login();
            login.setVisible(true);
        dispose();
        
            
        } else {
        // Display error message
            JOptionPane.showMessageDialog(null, registerResult);
        }
        
        
        //**************************************************************************************//
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }
    // Getter and Setter methods for txtUsername
    public String getTxtUsername() {
        return txtUsername.getText();
    }

    public void setTxtUsername(String txtUsername) {
        this.txtUsername.setText(txtUsername);
    }

    // Getter and Setter methods for txtPassword
    public String getTxtPassword() {
        return txtPassword.getText();
    }

    public void setTxtPassword(String txtPassword) {
        this.txtPassword.setText(txtPassword);
    }

    // Getter and Setter methods for txtFirstName
    public String getTxtFirstName() {
        return txtFirstName.getText();
    }

    public void setTxtFirstName(String txtFirstName) {
        this.txtFirstName.setText(txtFirstName);
    }

    // Getter and Setter methods for txtSurname
    public String getTxtSurname() {
        return txtSurname.getText();
    }

    public void setTxtSurname(String txtSurname) {
        this.txtSurname.setText(txtSurname);
    }

    // Getter and Setter methods for txaErrorUsername
    public String getTxaErrorUsername() {
        return txaErrorUsername.getText();
    }

    public void setTxaErrorUsername(String txaErrorUsername) {
        this.txaErrorUsername.setText(txaErrorUsername);
    }

    // Getter and Setter methods for txaErrorPassword
    public String getTxaErrorPassword() {
        return txaErrorPassword.getText();
    }

    public void setTxaErrorPassword(String txaErrorPassword) {
        this.txaErrorPassword.setText(txaErrorPassword);
    }

    // Getter and Setter methods for txaErrorFirstName
    public String getTxaErrorFirstName() {
        return txaErrorFirstName.getText();
    }

    public void setTxaErrorFirstName(String txaErrorFirstName) {
        this.txaErrorFirstName.setText(txaErrorFirstName);
    }

    // Getter and Setter methods for txaErrorSurname
    public String getTxaErrorSurname() {
        return txaErrorSurname.getText();
    }

    public void setTxaErrorSurname(String txaErrorSurname) {
        this.txaErrorSurname.setText(txaErrorSurname);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstNameLable;
    private javax.swing.JLabel PasswordLable;
    private javax.swing.JLabel SurnameLable;
    private javax.swing.JLabel UsernameLable;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txaErrorFirstName;
    private javax.swing.JTextArea txaErrorPassword;
    private javax.swing.JTextArea txaErrorSurname;
    private javax.swing.JTextArea txaErrorUsername;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
